
####### Expanded from @PACKAGE_INIT@ by configure_package_config_file() #######
####### Any changes to this file will be overwritten by the next CMake run ####
####### The input file was NuKEXCConfig.cmake.in                            ########

get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE)

macro(set_and_check _var _file)
  set(${_var} "${_file}")
  if(NOT EXISTS "${_file}")
    message(FATAL_ERROR "File or directory ${_file} referenced by variable ${_var} does not exist !")
  endif()
endmacro()

macro(check_required_components _NAME)
  foreach(comp ${${_NAME}_FIND_COMPONENTS})
    if(NOT ${_NAME}_${comp}_FOUND)
      if(${_NAME}_FIND_REQUIRED_${comp})
        set(${_NAME}_FOUND FALSE)
      endif()
    endif()
  endforeach()
endmacro()

####################################################################################

# 1. Include the macro to handle dependencies
include(CMakeFindDependencyMacro)

# 2. Re-find your library's required dependencies
# find_dependency is like find_package, but it propagates "REQUIRED" and "QUIET" 
# status from the parent call to find_package(NuKEXC).
find_dependency(Kokkos REQUIRED)
find_dependency(IntegratorXX REQUIRED)

# 3. Include the auto-generated targets file
# This is the file generated by your install(EXPORT ...) command.
include("${CMAKE_CURRENT_LIST_DIR}/NuKEXCTargets.cmake")

check_required_components(NuKEXC)
